import Head from 'next/head'
import { useRouter } from 'next/router'
import { useForm } from 'react-hook-form'
import styles from '../../styles/Login.module.css'
import * as Yup from 'yup'
import { yupResolver } from '@hookform/resolvers/yup';
import axios from 'axios';
import cookie from 'js-cookie'

const Login = () => {
  const router = useRouter();
  const validationSchema = Yup.object().shape({
    username: Yup.string()
              .required('Username is required'),
    password: Yup.string()
              .min(6, 'Password must be at least 6 characters')
              .required('Password is required')
  })  

  const formOptions = { resolver: yupResolver(validationSchema) }

  const { register, reset, handleSubmit, formState } = useForm(formOptions);
  const { errors } = formState

  function onSubmit(data) {
    return loginUser(data);
  }

  async function loginUser(value) {
    let config = {
      method: 'post',
      url: 'http://localhost:4000/api/auth/login',
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*'
      },
      data: value,
    };

    try {
      const response = await axios(config);
      if (response.status == 200) {
        cookie.set("token", response.data.access_token, { expires: 1 / 24 });
        reset();
        setTimeout(function(){}, 300)
        router.push("/dashboard")
      }
    } catch (err) {}
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Market App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Login
        </h1>

        <p className={styles.description}>
          Login into your account
        </p>

        <div className={styles.form}>
          <form onSubmit={handleSubmit(onSubmit)}>
            <input name="username" type="text" {...register('username')} className={`form-control ${errors.username ? styles.isinvalid : ''}`} placeholder="Username"/>
            <div className={styles.invalidfeedback}>{errors.username?.message}</div>

            <input name="password" type="password" {...register('password')} className={`form-control ${errors.password ? styles.isinvalid : ''}`} placeholder="Password" />
            <div className={styles.invalidfeedback}>{errors.password?.message}</div>

            <div className="form-group">
              <button type="submit" className="btn btn-primary mr-1">Login</button>
            </div>
          </form>
        </div>
      </main>

      <footer className={styles.footer}>
          Powered by{' '}
          <span className={styles.logo}>
            Erwin Wiguna
          </span>
      </footer>
    </div>
  )
}
export default Login